# Generated by Django 6.1.1 on 2026-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('current_location_coords', models.JSONField(blank=True, default=list)),
                ('pickup_location_coords', models.JSONField(blank=True, default=list)),
                ('dropoff_location_coords', models.JSONField(blank=True, default=list)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('daily_logs', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
