# Generated by Django 6.1.1 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_trip_span_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
