# Generated by Django 6.1.1 on 2026-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_cycle_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='co_driver_daily_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='co_driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='num_drivers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
