# Generated by Django 6.1.1 on 2026-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_co_driver_daily_logs_trip_co_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='restart_hours',
            field=models.FloatField(default=34.0),
        ),
    ]
