# Generated by Django 6.1.1 on 2026-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_restart_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cycle_cap_hours',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cycle_schedule',
            field=models.CharField(choices=[('70/8', '70-hour / 8-day'), ('60/7', '60-hour / 7-day'), ('custom', 'Custom')], default='70/8', max_length=10),
        ),
    ]
