# Generated by Django 6.1.1 on 2026-09-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_cycle_cap_hours_alter_trip_cycle_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cycle_cap_days',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
