# Generated by Django 6.1.1 on 2026-10-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_cycle_cap_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='co_driver_current_cycle_used_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
