# Generated by Django 6.1.1 on 2026-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_co_driver_current_cycle_used_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driving_hours_today',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='on_duty_hours_today',
            field=models.FloatField(default=0.0),
        ),
    ]
