# Generated by Django 6.1.1 on 2026-10-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_hours_used_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='days_past_14th_hour_this_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='exception_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='exception_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='farthest_air_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='operating_mode',
            field=models.CharField(choices=[('standard', 'Standard (§395.3)'), ('short_haul_cdl', 'CDL short-haul (§395.1(e)(1))'), ('short_haul_non_cdl', 'Non-CDL short-haul (§395.1(e)(2))')], default='standard', max_length=24),
        ),
        migrations.AddField(
            model_name='trip',
            name='return_to_reporting_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='use_16_hour_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='work_reporting_coords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='work_reporting_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
